--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -42,4 +42,4 @@
           cargo clippy --locked -- -D warnings
 
       - name: Run tests
-        run: cargo test --locked --verbose
+        run: cargo test --locked --verbose